[project]
name = "tamagonion"
version = "1.0.0"
description = "This is Stinky, he's running your Tor relay. He mostly loafs around and browses the Web anonymously, but he's more entertaining to look at than a graph!"
readme = "README.md"
authors = [
    { name = "Samuel De Grace", email = "48831884+daxAKAhackerman@users.noreply.github.com" }
]
requires-python = "==3.14.*"
dependencies = [
    "psutil==7.2.2",
    "stem==1.8.2",
]

[project.scripts]
tamagonion = "tamagonion:main"

[build-system]
requires = ["uv_build==0.12.3"]
build-backend = "uv_build"
